// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7myp8EhGEzMeymbBuLA8zMKKEUljHjpk',
    appId: '1:1087447912518:web:a344adda1c1edfba377a47',
    messagingSenderId: '1087447912518',
    projectId: 'spacex-a2b4c',
    authDomain: 'spacex-a2b4c.firebaseapp.com',
    storageBucket: 'spacex-a2b4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdzwUoFMpIXvlZHEsUWzqXSrJYvhiuoTI',
    appId: '1:1087447912518:android:20865d85a9f6982b377a47',
    messagingSenderId: '1087447912518',
    projectId: 'spacex-a2b4c',
    storageBucket: 'spacex-a2b4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBArgD2mnS-2oXYjufaMhtaIRB7p8jr638',
    appId: '1:1087447912518:ios:060b49bc52ebe304377a47',
    messagingSenderId: '1087447912518',
    projectId: 'spacex-a2b4c',
    storageBucket: 'spacex-a2b4c.appspot.com',
    iosBundleId: 'com.example.team1E1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7myp8EhGEzMeymbBuLA8zMKKEUljHjpk',
    appId: '1:1087447912518:web:f8cb910d2aa24f00377a47',
    messagingSenderId: '1087447912518',
    projectId: 'spacex-a2b4c',
    authDomain: 'spacex-a2b4c.firebaseapp.com',
    storageBucket: 'spacex-a2b4c.appspot.com',
  );
}
